// <auto-generated />
using CompanyApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyApp.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20240615034005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyApp.Models.Entity.Product", b =>
                {
                    b.Property<byte>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("P_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("ProductId"));

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Product_Category");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CompanyApp.Models.Entity.ProductDetail", b =>
                {
                    b.Property<byte>("ProductDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("PD_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("ProductDetailId"));

                    b.Property<byte>("ProductId")
                        .HasColumnType("tinyint")
                        .HasColumnName("P_Id");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProductDetailId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("CompanyApp.Models.Entity.ProductDetail", b =>
                {
                    b.HasOne("CompanyApp.Models.Entity.Product", "Products")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("CompanyApp.Models.Entity.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
